version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"  # PORT esplicito
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./frontend/images:/app/images  # 🔥 Monta le immagini nel backend
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5500:5500"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

volumes:
  backend_node_modules:
  frontend_node_modules:
  db_data:
